let brushSoftness=0;const softnessSliderEl=document.getElementById("softnessSlider");const softnessValueEl=document.getElementById("softnessValue");if(softnessSliderEl){softnessSliderEl.addEventListener("input",()=>{brushSoftness=Number(softnessSliderEl.value);if(softnessValueEl)softnessValueEl.textContent=brushSoftness+"%"})}
function withAlpha(hex,alpha){const[r,g,b]=hexToRgbArr(hex);return `rgba(${r},${g},${b},${alpha})`}
const previewCanvas=document.getElementById("previewCanvas");const previewCtx=previewCanvas?previewCanvas.getContext("2d"):null;function getPos(e){const rect=canvasArea.getBoundingClientRect();return{x:(e.clientX-rect.left-panX)/zoom,y:(e.clientY-rect.top-panY)/zoom}}
function stampBrush(x,y,pressure=1){const currentSize=brushSize*pressure;const radius=currentSize/2;const softness=Math.min(1,Math.max(0,brushSoftness/100));const isEraser=currentTool!=="brush";const ctx=(isEraser||!previewCtx)?colorCtx:previewCtx;const alphaScale=isEraser?brushOpacity:1;ctx.save();ctx.globalCompositeOperation=isEraser?"destination-out":"source-over";if(softness<=0.02){ctx.fillStyle=isEraser?"#000000":brushColor;ctx.globalAlpha=alphaScale;ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill()}else{const baseColor=isEraser?"#000000":brushColor;const innerStop=Math.max(0,1-softness);const grad=ctx.createRadialGradient(x,y,0,x,y,radius);grad.addColorStop(0,withAlpha(baseColor,alphaScale));grad.addColorStop(innerStop,withAlpha(baseColor,alphaScale));grad.addColorStop(1,withAlpha(baseColor,0));ctx.globalAlpha=1;ctx.fillStyle=grad;ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.fill()}
ctx.restore()}
function commitPreviewStroke(){if(!previewCanvas||!previewCtx)return;colorCtx.save();colorCtx.globalCompositeOperation="source-over";colorCtx.globalAlpha=brushOpacity;colorCtx.drawImage(previewCanvas,0,0);colorCtx.restore();previewCtx.clearRect(0,0,previewCanvas.width,previewCanvas.height);previewCanvas.style.opacity=1}
function stampBetweenPoints(p1,p2,pressure=1){const dx=p2.x-p1.x,dy=p2.y-p1.y;const dist=Math.sqrt(dx*dx+dy*dy);const currentSize=brushSize*pressure;const softness=Math.min(1,Math.max(0,brushSoftness/100));const spacingFactor=0.15-softness*0.08;const spacing=Math.max(1,currentSize*spacingFactor);const steps=Math.ceil(dist/spacing);for(let i=1;i<=steps;i++){stampBrush(p1.x+dx*(i/steps),p1.y+dy*(i/steps),pressure)}}
function sampleCanvasColor(x,y,radius){const r=Math.ceil(radius);const sx=Math.max(0,Math.round(x-r));const sy=Math.max(0,Math.round(y-r));const sw=Math.min(colorCanvas.width-sx,r*2);const sh=Math.min(colorCanvas.height-sy,r*2);if(sw<=0||sh<=0)return null;const data=colorCtx.getImageData(sx,sy,sw,sh).data;let rSum=0,gSum=0,bSum=0,aSum=0,count=0;for(let i=0;i<data.length;i+=4){if(data[i+3]>0){rSum+=data[i];gSum+=data[i+1];bSum+=data[i+2];aSum+=data[i+3];count++}}
return count===0?null:{r:rSum/count,g:gSum/count,b:bSum/count,a:aSum/count/255}}
function blendRgb(a,b,t){return{r:a.r+(b.r-a.r)*t,g:a.g+(b.g-a.g)*t,b:a.b+(b.b-a.b)*t}}
function stampMixer(x,y,pressure=1){const radius=(brushSize*pressure)/2;const canvas=sampleCanvasColor(x,y,radius);const[br,bg,bb]=hexToRgbArr(brushColor);const brushRgb={r:br,g:bg,b:bb};if(canvas&&canvas.a>0.01){if(!mixerColor)mixerColor={...brushRgb};mixerColor=blendRgb(mixerColor,{r:canvas.r,g:canvas.g,b:canvas.b},mixRatio)}else{if(!mixerColor)mixerColor={...brushRgb};mixerColor=blendRgb(mixerColor,brushRgb,0.05)}
colorCtx.save();colorCtx.globalCompositeOperation="source-over";colorCtx.globalAlpha=wetRatio*brushOpacity;const grad=colorCtx.createRadialGradient(x,y,0,x,y,radius);const mr=Math.round(mixerColor.r),mg=Math.round(mixerColor.g),mb=Math.round(mixerColor.b);grad.addColorStop(0,`rgba(${mr},${mg},${mb},1)`);grad.addColorStop(0.6,`rgba(${mr},${mg},${mb},0.6)`);grad.addColorStop(1,`rgba(${mr},${mg},${mb},0)`);colorCtx.fillStyle=grad;colorCtx.beginPath();colorCtx.arc(x,y,radius,0,Math.PI*2);colorCtx.fill();colorCtx.restore()}
function stampMixerBetweenPoints(p1,p2,pressure=1){const dx=p2.x-p1.x,dy=p2.y-p1.y;const dist=Math.sqrt(dx*dx+dy*dy);const radius=(brushSize*pressure)/2;const spacing=Math.max(1,radius*0.20);const steps=Math.ceil(dist/spacing);const canvas=sampleCanvasColor(p2.x,p2.y,radius);const[br,bg,bb]=hexToRgbArr(brushColor);const brushRgb={r:br,g:bg,b:bb};if(canvas&&canvas.a>0.01){if(!mixerColor)mixerColor={...brushRgb};mixerColor=blendRgb(mixerColor,{r:canvas.r,g:canvas.g,b:canvas.b},mixRatio)}else{if(!mixerColor)mixerColor={...brushRgb};mixerColor=blendRgb(mixerColor,brushRgb,0.05)}
for(let i=1;i<=steps;i++){const sx=p1.x+dx*(i/steps),sy=p1.y+dy*(i/steps);colorCtx.save();colorCtx.globalCompositeOperation="source-over";colorCtx.globalAlpha=wetRatio*brushOpacity;const grad=colorCtx.createRadialGradient(sx,sy,0,sx,sy,radius);const mr=Math.round(mixerColor.r),mg=Math.round(mixerColor.g),mb=Math.round(mixerColor.b);grad.addColorStop(0,`rgba(${mr},${mg},${mb},1)`);grad.addColorStop(0.6,`rgba(${mr},${mg},${mb},0.6)`);grad.addColorStop(1,`rgba(${mr},${mg},${mb},0)`);colorCtx.fillStyle=grad;colorCtx.beginPath();colorCtx.arc(sx,sy,radius,0,Math.PI*2);colorCtx.fill();colorCtx.restore()}}
function renderBrushLoop(){if(!drawing)return;const smoothing=0.45;brushPos.x+=(pointerPos.x-brushPos.x)*smoothing;brushPos.y+=(pointerPos.y-brushPos.y)*smoothing;brushPos.pressure+=(pointerPos.pressure-brushPos.pressure)*smoothing;const dist=Math.hypot(brushPos.x-previousPoint.x,brushPos.y-previousPoint.y);if(dist>0.5){if(currentTool==="mixer")stampMixerBetweenPoints(previousPoint,brushPos,brushPos.pressure);else stampBetweenPoints(previousPoint,brushPos,brushPos.pressure);previousPoint={...brushPos}}
renderLoopId=requestAnimationFrame(renderBrushLoop)}
canvasArea.addEventListener("pointerdown",e=>{if(isPalm(e)){rejectedPointers.add(e.pointerId);return}
if(isTouchBlocked())return;if(e.button===1||spaceHeld){isPanning=panMode=!0;startPanX=e.clientX;startPanY=e.clientY;canvasArea.style.cursor="grabbing";setBrushCursorVisible(!1);e.preventDefault();return}
if(e.button!==0)return;drawing=!0;activePointerId=e.pointerId;try{canvasArea.setPointerCapture(e.pointerId)}catch(err){}
const p=getPos(e);const pressure=(e.pointerType==='pen'&&e.pressure>0)?e.pressure:1;pointerPos={x:p.x,y:p.y,pressure};brushPos={x:p.x,y:p.y,pressure};previousPoint={...brushPos};if(currentTool==="mixer"){mixerColor=null;stampMixer(p.x,p.y,pressure)}else{if(currentTool==="brush"&&previewCanvas&&previewCtx){previewCtx.clearRect(0,0,previewCanvas.width,previewCanvas.height);previewCanvas.style.opacity=brushOpacity}
stampBrush(p.x,p.y,pressure)}
cancelAnimationFrame(renderLoopId);renderLoopId=requestAnimationFrame(renderBrushLoop)});window.addEventListener("pointermove",e=>{if(rejectedPointers.has(e.pointerId))return;const rect=canvasArea.getBoundingClientRect();const inArea=e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom;if(inArea||drawing){brushCursor.style.left=(e.clientX-rect.left)+"px";brushCursor.style.top=(e.clientY-rect.top)+"px"}
if(isPanning){panX+=e.clientX-startPanX;panY+=e.clientY-startPanY;startPanX=e.clientX;startPanY=e.clientY;updateViewport();return}
if(isTouchBlocked())return;if(!drawing||e.pointerId!==activePointerId)return;const p=getPos(e);const pressure=(e.pointerType==='pen'&&e.pressure>0)?e.pressure:1;pointerPos={x:p.x,y:p.y,pressure}});function endDrawing(e){if(rejectedPointers.has(e.pointerId)){rejectedPointers.delete(e.pointerId);return}
if(panMode||isPanning){isPanning=panMode=!1;canvasArea.style.cursor=spaceHeld?"grab":"";setBrushCursorVisible(!0);drawing=!1;previousPoint=null;activePointerId=null;return}
if(e.pointerId!==activePointerId)return;if(!drawing){previousPoint=null;activePointerId=null;try{canvasArea.releasePointerCapture(e.pointerId)}catch(err){}
return}
drawing=!1;cancelAnimationFrame(renderLoopId);if(previousPoint&&pointerPos){if(currentTool==="mixer")stampMixerBetweenPoints(previousPoint,pointerPos,pointerPos.pressure);else stampBetweenPoints(previousPoint,pointerPos,pointerPos.pressure)}
if(currentTool==="brush")commitPreviewStroke();saveState();previousPoint=null;activePointerId=null;try{canvasArea.releasePointerCapture(e.pointerId)}catch(err){}}
window.addEventListener("pointerup",endDrawing);window.addEventListener("pointercancel",endDrawing);const MAX_STATES=10;function saveInitialState(){undoStack=[colorCanvas.toDataURL()];redoStack=[]}
function saveState(){if(undoStack.length>=MAX_STATES)undoStack.shift();undoStack.push(colorCanvas.toDataURL());redoStack=[];scheduleAutoSave()}
function restoreState(dataURL){const img=new Image();img.src=dataURL;img.onload=()=>{colorCtx.clearRect(0,0,colorCanvas.width,colorCanvas.height);colorCtx.drawImage(img,0,0);scheduleAutoSave()}}
document.getElementById("undoBtn").onclick=()=>{if(undoStack.length<2)return;redoStack.push(undoStack.pop());restoreState(undoStack[undoStack.length-1])};document.getElementById("redoBtn").onclick=()=>{if(!redoStack.length)return;const state=redoStack.pop();if(undoStack.length>=MAX_STATES)undoStack.shift();undoStack.push(state);restoreState(state)};document.getElementById("saveBtn").onclick=async()=>{const exp=document.createElement("canvas");exp.width=colorCanvas.width;exp.height=colorCanvas.height;const ctx=exp.getContext("2d");ctx.fillStyle="white";ctx.fillRect(0,0,exp.width,exp.height);ctx.drawImage(colorCanvas,0,0);ctx.drawImage(lineCanvas,0,0);const manifestUrl=SITE_URL+"/atintaan/assets/lineart/manifest.json";let artistName="artist";try{const response=await fetch(manifestUrl);const manifest=await response.json();if(Array.isArray(manifest)){const currentFile=currentArtworkUrl?currentArtworkUrl.split("/").pop().split("?")[0]:"";const entry=manifest.find(m=>m.file===currentFile);if(entry&&entry.artist){artistName=entry.artist}else if(manifest.length>0){artistName=manifest[0].artist||"artist";console.warn("saveBtn: no manifest entry matched",currentFile,"— falling back to first entry")}}}catch(error){console.error("Failed to load or parse manifest.json from "+manifestUrl,error)}
const artistClean=artistName.replace(/\d+$/g,"").replace(/[_\-]+/g," ").replace(/\s+/g," ").trim().toLowerCase();const userPart=userName?userName.trim():"my";const filename=`${userPart} x ${artistClean}`.replace(/[\\/:*?"<>|]/g,"");const a=document.createElement("a");a.download=filename;a.href=exp.toDataURL("image/png");a.click()};document.getElementById("backBtn").onclick=()=>{switchScreen('galleryScreen');loadGallery()}
