function fitToScreen(){const w=canvasArea.clientWidth;const h=canvasArea.clientHeight;zoom=Math.min(w/imageWidth,h/imageHeight)*0.9;panX=(w-imageWidth*zoom)/2;panY=(h-imageHeight*zoom)/2;updateViewport()}
function updateViewport(){document.getElementById("canvasContainer").style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;updateBrushCursorSize()}
async function loadArtwork(url,name="Untitled"){switchScreen('app');revokeStaleURLs();currentArtworkUrl=url;currentArtworkName=name;const safeUrl=await fetchAndCacheImage(url);const img=new Image();img.crossOrigin="anonymous";img.onload=()=>{imageWidth=img.width;imageHeight=img.height;colorCanvas.width=imageWidth;colorCanvas.height=imageHeight;lineCanvas.width=imageWidth;lineCanvas.height=imageHeight;if(previewCanvas){previewCanvas.width=imageWidth;previewCanvas.height=imageHeight}
document.getElementById('canvasContainer').style.width=imageWidth+'px';document.getElementById('canvasContainer').style.height=imageHeight+'px';lineCtx.clearRect(0,0,imageWidth,imageHeight);lineCtx.drawImage(img,0,0);colorCtx.clearRect(0,0,imageWidth,imageHeight);fitToScreen();saveInitialState();scheduleAutoSave()};img.src=safeUrl}
canvasArea.addEventListener("wheel",e=>{e.preventDefault();const factor=e.deltaY>0?0.9:1.1;const rect=canvasArea.getBoundingClientRect();const beforeX=(e.clientX-rect.left-panX)/zoom;const beforeY=(e.clientY-rect.top-panY)/zoom;zoom=Math.max(0.1,Math.min(zoom*factor,20));panX=(e.clientX-rect.left)-beforeX*zoom;panY=(e.clientY-rect.top)-beforeY*zoom;updateViewport()},{passive:!1});let touchState={active:!1,startDist:0,startZoom:1,startMidX:0,startMidY:0,startPanX:0,startPanY:0};let activePointerCount=0;const PALM_RADIUS_THRESHOLD=30;function isPalm(e){if(e.pointerType==="pen")return!1;if(e.pointerType==="mouse")return!1;const w=e.width??0;const h=e.height??0;return(w>PALM_RADIUS_THRESHOLD||h>PALM_RADIUS_THRESHOLD)}
const rejectedPointers=new Set();function getTouchMid(touches){const rect=canvasArea.getBoundingClientRect();return{x:((touches[0].clientX+touches[1].clientX)/2)-rect.left,y:((touches[0].clientY+touches[1].clientY)/2)-rect.top}}
function getTouchDist(touches){const dx=touches[0].clientX-touches[1].clientX;const dy=touches[0].clientY-touches[1].clientY;return Math.sqrt(dx*dx+dy*dy)}
function abortStroke(){if(!drawing)return;drawing=!1;cancelAnimationFrame(renderLoopId);activePointerId=null;if(previewCanvas&&previewCtx){previewCtx.clearRect(0,0,previewCanvas.width,previewCanvas.height);previewCanvas.style.opacity=1}
if(undoStack.length){const snapUrl=undoStack[undoStack.length-1];const img=new Image();img.onload=()=>{colorCtx.clearRect(0,0,colorCanvas.width,colorCanvas.height);colorCtx.drawImage(img,0,0);previousPoint=null};img.src=snapUrl}else{previousPoint=null}}
canvasArea.addEventListener("touchstart",e=>{if(e.touches.length===2){abortStroke();touchState.active=!0;touchState.startDist=getTouchDist(e.touches);touchState.startZoom=zoom;const mid=getTouchMid(e.touches);touchState.startMidX=mid.x;touchState.startMidY=mid.y;touchState.startPanX=panX;touchState.startPanY=panY;e.preventDefault()}},{passive:!1});canvasArea.addEventListener("touchmove",e=>{if(e.touches.length===2&&touchState.active){e.preventDefault();const dist=getTouchDist(e.touches);const mid=getTouchMid(e.touches);const newZoom=Math.max(0.1,Math.min(touchState.startZoom*(dist/touchState.startDist),20));const originX=(touchState.startMidX-touchState.startPanX)/touchState.startZoom;const originY=(touchState.startMidY-touchState.startPanY)/touchState.startZoom;panX=touchState.startMidX-originX*newZoom+(mid.x-touchState.startMidX);panY=touchState.startMidY-originY*newZoom+(mid.y-touchState.startMidY);zoom=newZoom;updateViewport()}},{passive:!1});canvasArea.addEventListener("touchend",e=>{if(touchState.active&&e.touches.length<2){touchState.active=!1;activePointerCount=0;drawing=!1;previousPoint=null;activePointerId=null}},{passive:!1});canvasArea.addEventListener("touchcancel",e=>{touchState.active=!1;activePointerCount=0;drawing=!1;previousPoint=null;activePointerId=null},{passive:!1});canvasArea.addEventListener("dragstart",e=>e.preventDefault());canvasArea.addEventListener("pointerdown",e=>{activePointerCount++;if(activePointerCount>1){abortStroke()}},{capture:!0,passive:!0});document.addEventListener("pointerup",e=>{activePointerCount=Math.max(0,activePointerCount-1)},{capture:!0,passive:!0});document.addEventListener("pointercancel",e=>{activePointerCount=Math.max(0,activePointerCount-1)},{capture:!0,passive:!0});function isTouchBlocked(){return touchState.active||activePointerCount>1}
