let activeFilter="all";let allGalleryFiles=[];const FINISHED_THRESHOLD=0.85;const SAMPLE_STEP=4;async function computeCompletionRatio(saved){if(!saved||!saved.colorBlob)return 0;return new Promise(resolve=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.width;c.height=img.height;const ctx=c.getContext("2d",{willReadFrequently:!0});ctx.drawImage(img,0,0);const data=ctx.getImageData(0,0,c.width,c.height).data;let colored=0;let total=0;for(let i=3;i<data.length;i+=4*SAMPLE_STEP){total++;if(data[i]>10)colored++}
resolve(total===0?0:colored/total)};img.onerror=()=>resolve(0);img.src=URL.createObjectURL(saved.colorBlob)})}
async function getArtworkStatus(file){const saved=await dbGet(file.data);if(!saved)return{status:"new",saved:null,ratio:0};const ratio=await computeCompletionRatio(saved);return{status:ratio>=FINISHED_THRESHOLD?"finished":"in-progress",saved,ratio}}
function buildCard(file,status,saved){const card=document.createElement("div");card.className="card";card.setAttribute("data-url",file.data);card.setAttribute("data-status",status);const thumbSrc=saved?saved.thumb:(file.thumbnail||"");let badgeHTML="";if(status==="in-progress"){badgeHTML=`<div class="progress-badge progress-badge--wip">🎨 In Progress</div>`}else if(status==="finished"){badgeHTML=`<div class="progress-badge progress-badge--done">🏅 Finished!</div>`}
card.innerHTML=`<img src="${thumbSrc}" loading="lazy"><h3>${file.name}</h3>${badgeHTML}`;if(!saved&&file.thumbnail){fetchAndCacheImage(file.thumbnail).then(src=>{const img=card.querySelector("img");if(img)img.src=src})}
card.onclick=async()=>{if(saved)await resumeSession(saved);else loadArtwork(file.data,file.name)};return card}
function renderFiltered(){gallery.innerHTML="";const filtered=activeFilter==="all"?allGalleryFiles:allGalleryFiles.filter(f=>f._status===activeFilter);if(filtered.length===0){gallery.innerHTML=`<p class="gallery-empty">Nothing here yet! Start coloring to fill this section. 🎨</p>`;return}
filtered.forEach(f=>{gallery.appendChild(buildCard(f,f._status,f._saved))})}
async function renderGalleryItems(files){gallery.innerHTML=`<p class="gallery-loading">Loading your artworks…</p>`;const enriched=await Promise.all(files.map(async file=>{const{status,saved}=await getArtworkStatus(file);return{...file,_status:status,_saved:saved}}));allGalleryFiles=enriched;updateFilterCounts();renderFiltered();enriched.forEach(f=>{if(!f._saved)fetchAndCacheImage(f.data);})}
async function loadGallery(){const MANIFEST=LINEART_URL+"manifest.json";const cachedJSON=localStorage.getItem("galleryList");if(cachedJSON){try{await renderGalleryItems(JSON.parse(cachedJSON))}catch(e){console.warn("Cache parse failed.",e)}}
try{const res=await fetch(MANIFEST+"?t="+Date.now());if(!res.ok)throw new Error("Manifest fetch failed: "+res.status);const items=await res.json();const files=items.map(item=>({id:item.file,name:item.name,thumbnail:LINEART_URL+item.file,data:LINEART_URL+item.file}));const fresh=JSON.stringify(files);if(fresh!==cachedJSON){localStorage.setItem("galleryList",fresh);await renderGalleryItems(files)}}catch(err){if(!cachedJSON){gallery.innerHTML=`<p class="gallery-empty">
                Could not load gallery. Check your connection and try again.</p>`}
console.warn("Gallery manifest load failed:",err)}}
function updateFilterCounts(){const counts={all:allGalleryFiles.length,new:0,"in-progress":0,finished:0};allGalleryFiles.forEach(f=>{if(counts[f._status]!==undefined)counts[f._status]++});document.querySelectorAll(".filter-chip").forEach(chip=>{const key=chip.dataset.filter;const count=counts[key]??0;const badge=chip.querySelector(".chip-count");if(badge)badge.textContent=count;chip.classList.toggle("filter-chip--empty",count===0&&key!=="all")})}
function initFilterChips(){document.querySelectorAll(".filter-chip").forEach(chip=>{chip.addEventListener("click",()=>{document.querySelectorAll(".filter-chip").forEach(c=>c.classList.remove("active"));chip.classList.add("active");activeFilter=chip.dataset.filter;renderFiltered()})})}
