const DB_NAME="coloringBookApp";const DB_VERSION=3;const STORE="sessions";const CACHE_STORE="galleryCache";let db=null;function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=e=>{if(e.target.result.objectStoreNames.contains("session")){e.target.result.deleteObjectStore("session")}
if(!e.target.result.objectStoreNames.contains(STORE)){e.target.result.createObjectStore(STORE)}
if(!e.target.result.objectStoreNames.contains(CACHE_STORE)){e.target.result.createObjectStore(CACHE_STORE)}};req.onsuccess=e=>resolve(e.target.result);req.onerror=e=>reject(e.target.error)})}
async function dbPut(key,value,storeName=STORE){if(!db)return;return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,"readwrite");const req=tx.objectStore(storeName).put(value,key);req.onsuccess=()=>resolve();req.onerror=e=>reject(e.target.error)})}
async function dbGet(key,storeName=STORE){if(!db)return null;return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,"readonly");const req=tx.objectStore(storeName).get(key);req.onsuccess=e=>resolve(e.target.result??null);req.onerror=e=>reject(e.target.error)})}
async function dbDelete(key,storeName=STORE){if(!db)return;return new Promise((resolve,reject)=>{const tx=db.transaction(storeName,"readwrite");const req=tx.objectStore(storeName).delete(key);req.onsuccess=()=>resolve();req.onerror=e=>reject(e.target.error)})}
const objectURLsToRevoke=new Set();function safeCreateObjectURL(blob){const url=URL.createObjectURL(blob);objectURLsToRevoke.add(url);return url}
function revokeStaleURLs(){objectURLsToRevoke.forEach(url=>URL.revokeObjectURL(url));objectURLsToRevoke.clear()}
async function fetchAndCacheImage(url){try{const cached=await dbGet(url,CACHE_STORE);if(cached&&cached.blob)return safeCreateObjectURL(cached.blob);const res=await fetch(url,{mode:'cors'});if(!res.ok)throw new Error("Network response failed");const blob=await res.blob();await dbPut(url,{blob},CACHE_STORE);return safeCreateObjectURL(blob)}catch(err){return url}}
let autoSaveTimer=null;function scheduleAutoSave(){clearTimeout(autoSaveTimer);autoSaveTimer=setTimeout(persistSession,1000)}
async function persistSession(){if(!currentArtworkUrl)return;const thumbCanvas=document.createElement("canvas");const scale=Math.min(1,200/colorCanvas.width);thumbCanvas.width=Math.round(colorCanvas.width*scale);thumbCanvas.height=Math.round(colorCanvas.height*scale);const tCtx=thumbCanvas.getContext("2d");tCtx.fillStyle="white";tCtx.fillRect(0,0,thumbCanvas.width,thumbCanvas.height);tCtx.drawImage(colorCanvas,0,0,thumbCanvas.width,thumbCanvas.height);tCtx.drawImage(lineCanvas,0,0,thumbCanvas.width,thumbCanvas.height);const thumb=thumbCanvas.toDataURL("image/jpeg",0.6);colorCanvas.toBlob(async blob=>{await dbPut(currentArtworkUrl,{artworkUrl:currentArtworkUrl,artworkName:currentArtworkName,colorBlob:blob,thumb:thumb,timestamp:Date.now()});localStorage.setItem("lastActiveUrl",currentArtworkUrl);updateGalleryThumb(currentArtworkUrl,thumb)},"image/png")}
function updateGalleryThumb(url,thumbDataUrl){const cardImg=document.querySelector(`.card[data-url="${url}"] img`);if(cardImg)cardImg.src=thumbDataUrl;const cardBadge=document.querySelector(`.card[data-url="${url}"] .progress-badge`);if(!cardBadge){const card=document.querySelector(`.card[data-url="${url}"]`);if(card)card.innerHTML+=`<div class="progress-badge">⭐ In Progress</div>`}}
async function checkResumeBanner(){const lastUrl=localStorage.getItem("lastActiveUrl");if(!lastUrl)return;const saved=await dbGet(lastUrl);if(!saved)return;const banner=document.getElementById("resumeBanner");document.getElementById("resumeThumb").src=saved.thumb;document.getElementById("resumeName").textContent=saved.artworkName||"Untitled";banner.style.display="flex";document.getElementById("resumeYesBtn").onclick=async()=>{banner.style.display="none";await resumeSession(saved)};document.getElementById("resumeNoBtn").onclick=async()=>{banner.style.display="none";await dbDelete(lastUrl);localStorage.removeItem("lastActiveUrl");loadGallery()}}
async function resumeSession(saved){switchScreen('app');revokeStaleURLs();const safeUrl=await fetchAndCacheImage(saved.artworkUrl);const lineImg=new Image();lineImg.crossOrigin="anonymous";lineImg.onload=()=>{imageWidth=lineImg.width;imageHeight=lineImg.height;colorCanvas.width=imageWidth;colorCanvas.height=imageHeight;lineCanvas.width=imageWidth;lineCanvas.height=imageHeight;document.getElementById('canvasContainer').style.width=imageWidth+'px';document.getElementById('canvasContainer').style.height=imageHeight+'px';lineCtx.clearRect(0,0,imageWidth,imageHeight);lineCtx.drawImage(lineImg,0,0);currentArtworkUrl=saved.artworkUrl;currentArtworkName=saved.artworkName;const colorUrl=safeCreateObjectURL(saved.colorBlob);const colorImg=new Image();colorImg.onload=()=>{colorCtx.clearRect(0,0,imageWidth,imageHeight);colorCtx.drawImage(colorImg,0,0);fitToScreen();saveInitialState()};colorImg.src=colorUrl};lineImg.src=safeUrl}