(()=>{const colorCanvas=document.getElementById('layer-color');const lineartCanvas=document.getElementById('layer-lineart');const colorCtx=colorCanvas.getContext('2d');const lineartCtx=lineartCanvas.getContext('2d');const squareEl=document.getElementById('canvas-square');const transformWrap=document.getElementById('canvas-transform-wrap');const toolState={activeLayer:'lineart',tool:'brush',color:'#2b2a3d',size:8,drawing:!1,lastX:0,lastY:0,};let canvasesReady=!1;function initCanvasesIfNeeded(){resetView();if(canvasesReady)return;canvasesReady=!0;sizeCanvasToSquare(colorCanvas);sizeCanvasToSquare(lineartCanvas);lineartCtx.lineCap='round';lineartCtx.lineJoin='round';colorCtx.lineCap='round';colorCtx.lineJoin='round';window.addEventListener('resize',()=>{const colorSnap=colorCanvas.toDataURL();const lineSnap=lineartCanvas.toDataURL();sizeCanvasToSquare(colorCanvas);sizeCanvasToSquare(lineartCanvas);restoreSnapshot(colorCtx,colorCanvas,colorSnap);restoreSnapshot(lineartCtx,lineartCanvas,lineSnap)})}
function sizeCanvasToSquare(canvas){const rect=squareEl.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0)}
function restoreSnapshot(ctx,canvas,dataUrl){const img=new Image();img.onload=()=>{const dpr=window.devicePixelRatio||1;ctx.drawImage(img,0,0,canvas.width/dpr,canvas.height/dpr)};img.src=dataUrl}
function preloadExistingLayers(myRecord){if(!myRecord)return Promise.resolve();return Promise.all([drawImageUrlOnto(colorCtx,colorCanvas,myRecord.color_url),drawImageUrlOnto(lineartCtx,lineartCanvas,myRecord.lineart_url),])}
function drawImageUrlOnto(ctx,canvas,url){return new Promise((resolve)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{const dpr=window.devicePixelRatio||1;ctx.drawImage(img,0,0,canvas.width/dpr,canvas.height/dpr);resolve()};img.onerror=()=>resolve();img.src=url})}
const MIN_ZOOM=0.5,MAX_ZOOM=6;let cam={x:0,y:0,scale:1};function clamp(v,lo,hi){return Math.max(lo,Math.min(hi,v))}
function applyCam(){transformWrap.style.transform=`translate(${cam.x}px, ${cam.y}px) scale(${cam.scale})`}
function resetView(){cam={x:0,y:0,scale:1};applyCam()}
document.getElementById('btn-reset-view').addEventListener('click',resetView);function getPos(e){const rect=squareEl.getBoundingClientRect();const localX=e.clientX-rect.left;const localY=e.clientY-rect.top;return{x:(localX-cam.x)/cam.scale,y:(localY-cam.y)/cam.scale}}
squareEl.addEventListener('wheel',(e)=>{e.preventDefault();const delta=-e.deltaY*0.0015;const newScale=clamp(cam.scale*(1+delta),MIN_ZOOM,MAX_ZOOM);const rect=squareEl.getBoundingClientRect();const localX=e.clientX-rect.left,localY=e.clientY-rect.top;const innerX=(localX-cam.x)/cam.scale,innerY=(localY-cam.y)/cam.scale;cam.scale=newScale;cam.x=localX-innerX*newScale;cam.y=localY-innerY*newScale;applyCam()},{passive:!1});const activePointers=new Map();let drawingPointerId=null;let panPointerId=null;let panStart=null,panCamStart=null;let gesture=null;let suppressUntilEmpty=!1;function twoActivePoints(){const pts=[...activePointers.values()];return pts.length>=2?[pts[0],pts[1]]:null}
function beginGesture(){const pts=twoActivePoints();if(!pts)return;const rect=squareEl.getBoundingClientRect();const startMid={x:(pts[0].x+pts[1].x)/2-rect.left,y:(pts[0].y+pts[1].y)/2-rect.top};gesture={rect,startDist:Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)||1,startScale:cam.scale,anchor:{x:(startMid.x-cam.x)/cam.scale,y:(startMid.y-cam.y)/cam.scale},}}
function updateGesture(){const pts=twoActivePoints();if(!gesture||!pts)return;const dist=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)||1;const mid={x:(pts[0].x+pts[1].x)/2-gesture.rect.left,y:(pts[0].y+pts[1].y)/2-gesture.rect.top};const newScale=clamp(gesture.startScale*(dist/gesture.startDist),MIN_ZOOM,MAX_ZOOM);cam.scale=newScale;cam.x=mid.x-gesture.anchor.x*newScale;cam.y=mid.y-gesture.anchor.y*newScale;applyCam()}
function endGesture(){gesture=null}
function activeCanvasCtx(){return toolState.activeLayer==='lineart'?lineartCtx:colorCtx}
function effectiveWidth(e){const pressure=(e.pointerType==='pen'&&e.pressure>0)?e.pressure:1;return Math.max(1,toolState.size*pressure)}
function drawDot(x,y,e){const ctx=activeCanvasCtx();ctx.save();ctx.globalCompositeOperation=toolState.tool==='eraser'?'destination-out':'source-over';ctx.fillStyle=toolState.color;const w=effectiveWidth(e);ctx.beginPath();ctx.arc(x,y,w/2,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawLine(x1,y1,x2,y2,e){const ctx=activeCanvasCtx();ctx.save();ctx.globalCompositeOperation=toolState.tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=toolState.color;ctx.lineWidth=effectiveWidth(e);ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore()}
function onPointerDown(e){squareEl.setPointerCapture(e.pointerId);activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(e.button===1){e.preventDefault();panPointerId=e.pointerId;panStart={x:e.clientX,y:e.clientY};panCamStart={x:cam.x,y:cam.y};squareEl.classList.add('panning');return}
if(suppressUntilEmpty)return;if(activePointers.size===2){if(drawingPointerId!==null){toolState.drawing=!1;drawingPointerId=null}
beginGesture();return}
if(activePointers.size>2||gesture){return}
e.preventDefault();drawingPointerId=e.pointerId;toolState.drawing=!0;const p=getPos(e);toolState.lastX=p.x;toolState.lastY=p.y;drawDot(p.x,p.y,e)}
function onPointerMove(e){if(activePointers.has(e.pointerId)){activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY})}
if(e.pointerId===panPointerId){cam.x=panCamStart.x+(e.clientX-panStart.x);cam.y=panCamStart.y+(e.clientY-panStart.y);applyCam();return}
if(gesture){updateGesture();return}
trackCursorIndicator(e);if(e.pointerId!==drawingPointerId||!toolState.drawing)return;const p=getPos(e);drawLine(toolState.lastX,toolState.lastY,p.x,p.y,e);toolState.lastX=p.x;toolState.lastY=p.y}
function onPointerUp(e){activePointers.delete(e.pointerId);if(e.pointerId===panPointerId){panPointerId=null;squareEl.classList.remove('panning')}
if(e.pointerId===drawingPointerId){drawingPointerId=null;toolState.drawing=!1}
if(gesture&&activePointers.size<2){endGesture();if(activePointers.size>0)suppressUntilEmpty=!0}
if(activePointers.size===0){suppressUntilEmpty=!1}}
const cursorIndicator=document.getElementById('brush-cursor');let lastCursorX=null,lastCursorY=null;function trackCursorIndicator(e){const p=getPos(e);lastCursorX=p.x;lastCursorY=p.y;refreshCursorIndicator()}
function refreshCursorIndicator(){if(lastCursorX===null)return;cursorIndicator.style.left=`${lastCursorX}px`;cursorIndicator.style.top=`${lastCursorY}px`;cursorIndicator.style.width=`${toolState.size}px`;cursorIndicator.style.height=`${toolState.size}px`;cursorIndicator.classList.toggle('is-eraser',toolState.tool==='eraser');cursorIndicator.style.borderColor=toolState.tool==='eraser'?'':toolState.color}
function showCursorIndicator(){cursorIndicator.classList.add('visible')}
function hideCursorIndicator(){cursorIndicator.classList.remove('visible')}
squareEl.addEventListener('pointerdown',onPointerDown);squareEl.addEventListener('pointermove',onPointerMove);squareEl.addEventListener('pointerup',onPointerUp);squareEl.addEventListener('pointercancel',onPointerUp);squareEl.addEventListener('pointerenter',showCursorIndicator);squareEl.addEventListener('pointerleave',hideCursorIndicator);squareEl.addEventListener('contextmenu',(e)=>e.preventDefault());document.querySelectorAll('.seg-btn[data-layer]').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.seg-btn[data-layer]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');toolState.activeLayer=btn.dataset.layer})});document.querySelectorAll('.seg-btn[data-tool]').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.seg-btn[data-tool]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');toolState.tool=btn.dataset.tool;refreshCursorIndicator()})});document.getElementById('input-size').addEventListener('input',(e)=>{toolState.size=parseInt(e.target.value,10);document.getElementById('size-readout').textContent=toolState.size;refreshCursorIndicator()});document.getElementById('btn-clear-layer').addEventListener('click',()=>{const canvas=toolState.activeLayer==='lineart'?lineartCanvas:colorCanvas;const ctx=toolState.activeLayer==='lineart'?lineartCtx:colorCtx;const dpr=window.devicePixelRatio||1;ctx.clearRect(0,0,canvas.width/dpr,canvas.height/dpr)});function canvasToBlob(canvas){return new Promise((resolve)=>canvas.toBlob((b)=>resolve(b),'image/png'))}
function flattenLayers(){const w=colorCanvas.width,h=colorCanvas.height;const out=document.createElement('canvas');out.width=w;out.height=h;const octx=out.getContext('2d');octx.drawImage(colorCanvas,0,0);octx.drawImage(lineartCanvas,0,0);return Promise.all([canvasToBlob(lineartCanvas),canvasToBlob(colorCanvas),canvasToBlob(out),]).then(([lineartBlob,colorBlob,finalBlob])=>({lineartBlob,colorBlob,finalBlob}))}
window.App=window.App||{};window.App.draw={initCanvasesIfNeeded,preloadExistingLayers,flattenLayers,getColor:()=>toolState.color,setColor:(hex)=>{toolState.color=hex;refreshCursorIndicator()},}})()
